const reporter = require('cucumber-html-reporter');
var date = new Date ();
var currentDate = date.getDate() + '_' + (date.getMonth()+1) + '_' +date.getFullYear() + '_'
                        + date.getHours() + '_' + date.getMinutes() + '_' + date.getSeconds() + '_' + date.getMilliseconds();
 
const options = {
    theme: 'bootstrap',
    jsonFile: './reports/cucumber_report.json',
    output: './reports/cucumber_report'+ currentDate +'.html',
    reportSuiteAsScenarios: true,
    scenarioTimestamp: true,
    launchReport: true,
    metadata: {
        "App Version": "1.0.0",
        "Test Environment": "STAGING",
        "Browser": "Chromium",
        "Platform": "Windows 11",
        "Generated by": "Quentinos"
    }
};
 
reporter.generate(options);